//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.21 at 05:47:10 PM PST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://saras.lbl.gov/courses", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package gov.lbl.saras.courses;
